<?php

namespace Database\Seeders;

use App\Models\RegionState;
use App\Models\Township;
use Illuminate\Database\Seeder;

class LocationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $locations = [
            [
                'name' => 'Kachin State',
                'townships' => ['Kawnglanghpu', 'Waingmaw', 'Pannandin', 'Sumprabum', 'Nogmung', 'Putao', 'Machanbaw', 'Bhamo', 'Mansi', 'Momauk', 'Shwegu', 'Chipwi', 'Hsawlaw', 'Tanai', 'Myitkyina', 'Injangyang', 'Hpakan', 'Mogaung', 'Mohnyin'],
            ],
            [
                'name' => 'Kayah State',
                'townships' => ['Loikaw', 'Demoso', 'Hpruso', 'Shadaw', 'Bawlakhe', 'Hpasawng', 'Mese'],
            ],
            [
                'name' => 'Kayin State',
                'townships' => ['Hpa-an', 'Hlaingnbwe', 'Thandaunggyi', 'Hpapun', 'Myawaddy', 'Paingkyon', 'Kamamaung', 'Kawkareik', 'Kyainseikgyi', 'Bawgali', 'Leiktho'],
            ],
            [
                'name' => 'Chin State',
                'townships' => ['Hakha', 'Htantlang', 'Falam', 'Tiddim', 'Tonzang', 'Mindat', 'Matupi', 'Kanpetlet', 'Paletwa', 'Rikhuadal', 'Reazu'],
            ],
            [
                'name' => 'Sagaing Region',
                'townships' => [
                    'Sagaing',
                    'Myinmu',
                    'Myaung',
                    'Shwebo',
                    'Khin-U',
                    'Wetlet',
                    'Kanbalu',
                    'Kyunhla',
                    'Ye-U',
                    'Tabayin',
                    'Taze',
                    'Monywa',
                    'Budalin',
                    'Ayadaw',
                    'Chaung-U',
                    'Katha',
                    'Indaw',
                    'Tigyaing',
                    'Banmauk',
                    'Kawlin',
                    'Wuntho',
                    'Pinlebu',
                    'Kale',
                    'Kalewa',
                    'Mingin',
                    'Tamu',
                    'Mawlaik',
                    'Paungbyin',
                    'Kani',
                    'Homalin',
                    'Leshi',
                    'Lahe',
                    'Nanyun',
                    'Yinmabin',
                    'Salingyi',
                    'Pale',
                    'Kanii',
                    'Khampat',
                    'Myothitt',
                    'Pansaung',
                ],
            ],
            [
                'name' => 'Tanintharyi Region',
                'townships' => [
                    'Dawei',
                    'Launglon',
                    'Thayetchaung',
                    'Yebyu',
                    'Myeik',
                    'Kyunsu',
                    'Palaw',
                    'Tanintharyi',
                    'Kawthoung',
                    'Bokpyin',
                    'Myitta',
                    'Kaleinaung',
                    'Palauk',
                    'Khamaukgyi',
                    'Karathuri',
                    'Pyigyimandaing',
                ],
            ],
            [
                'name' => 'Bago Region',
                'townships' => [
                    'Bago',
                    'Thanatpin',
                    'Kawa',
                    'Waw',
                    'Naunglebin',
                    'Kyauktaga',
                    'Daik-U',
                    'Shwegyin',
                    'Taungoo',
                    'Yedashe',
                    'Kyaukkyi',
                    'Pyu',
                    'Oktwin',
                    'Tantabin',
                    'Pyay',
                    'Paukkaung',
                    'Padaung',
                    'Paungde',
                    'Thegon',
                    'Shwedaung',
                    'Thayarwady',
                    'Letpadan',
                    'Minnhla',
                    'Okpho',
                    'Zigon',
                    'Nattalin',
                    'Monyo',
                    'Gyobingauk',
                ],
            ],
            [
                'name' => 'Magway Region',
                'townships' => [
                    'Magway',
                    'Yenangyaung',
                    'Chauck',
                    'Taungdwingyi',
                    'Myothit',
                    'Natmauk',
                    'Minbu',
                    'Pwintbyu',
                    'Ngape',
                    'Salin',
                    'Sidoktaya',
                    'Thayet',
                    'Minhla',
                    'Mindon',
                    'Kamma',
                    'Aunglan',
                    'Sinbaungwe',
                    'Pakokku',
                    'Yesagyo',
                    'Myaing',
                    'Pauk',
                    'Seikphyu',
                    'Gangaw',
                    'Tilin',
                    'Saw',
                    'Kyaukhtu',
                ],
            ],
            [
                'name' => 'Mandalay Region',
                'townships' => [
                    'Aungmyethazan',
                    'Chanmyathazan',
                    'Mahaaungmye',
                    'Chanmyathazi',
                    'Pyigyidagun',
                    'Amarapura',
                    'Patheingyi',
                    'Pyinoolwin',
                    'Madaya',
                    'Singu',
                    'Mogok',
                    'Thabeikkyin',
                    'Kyaukse',
                    'Sintgaing',
                    'Myittha',
                    'Tada-U',
                    'Myingyan',
                    'Thaungtha',
                    'Natogyi',
                    'Kyaukpadaung',
                    'Nganzun',
                    'Nyaung-U',
                    'Yamethin',
                    'Pyawbwe',
                    'Meiktila',
                    'Mahlaing',
                    'Thazi',
                    'Wundwin',
                    'Tagaung',
                    'Ngathayauk',
                ],
            ],
            [
                'name' => 'Mon State',
                'townships' => [
                    'Mawlamyine',
                    'Kyaikmaraw',
                    'Chaungzon',
                    'Thanbyuzayat',
                    'Mudon',
                    'Ye',
                    'Thaton',
                    'Paung',
                    'Kyaikto',
                    'Bilin',
                    'Lamine',
                    'Kyaikkhami',
                ],
            ],
            [
                'name' => 'Rakhine State',
                'townships' => [
                    'Sittwe',
                    'Ponnagyun',
                    'Pauktaw',
                    'Rathedaung',
                    'Mrauk-U',
                    'Kyauktaw',
                    'Minbya',
                    'Myebon',
                    'Maungdaw',
                    'Buthidaung',
                    'Kyaukpyu',
                    'Manaung',
                    'Ramree',
                    'Thandwe',
                    'Toungup',
                    'Gaw',
                    'Taungpyoletwe',
                    'Maei',
                    'Kyeintali',
                ],
            ],
            [
                'name' => 'Yangon Region',
                'townships' => [
                    'Insein',
                    'Mingaladon',
                    'Hmawbi',
                    'Hlegu',
                    'Taikkyi',
                    'Htantabin',
                    'Shwepyitha',
                    'Hlaingthaya',
                    'Thingangyun',
                    'Yankin',
                    'SouthDagon',
                    'NorthOkkalapa',
                    'Thaketa',
                    'Dawbon',
                    'Tamwe',
                    'Pazundaung',
                    'Botataung',
                    'SouthOkkalapa',
                    'NorthDagon',
                    'EastDagon',
                    'DagonSeikkan',
                    'MingalaTaungnyunt',
                    'Thanlyin',
                    'Kyawuktan',
                    'Thongwa',
                    'Kayan',
                    'Twante',
                    'Kawhmu',
                    'Kungyangon',
                    'Dala',
                    'Seikkyi/Kanaungto',
                    'Cocoekyun',
                    'Kyauktada',
                    'Pabedan',
                    'Lanmadaw',
                    'Latha',
                    'Ahlon',
                    'Kyimyindaing',
                    'Sanchaung',
                    'Hlaing',
                    'Kamayut',
                    'Mayangon',
                    'Dagon',
                    'Bahan',
                    'Seikkan',
                    'Tada',
                ],
            ],
            [
                'name' => 'Shan State(South)',
                'townships' => [
                    'Kalaw',
                    'Nyaungshwe',
                    'Taunggyi',
                    'Pekon',
                    'Lawksawk',
                    'Pingdaya',
                    'Ywangan',
                    'Hsihseng',
                    'Pinlaung',
                    'Hopong',
                    'Mongnai',
                    'Mongpan',
                    'Mawkmai',
                    'Langkho',
                    'Kyethi',
                    'Kunhing',
                    'Nansang',
                    'Mongkung',
                    'Monghsu',
                    'Loilen',
                    'Laihka',
                    'Kyauktalongyi',
                    'Naungtayar',
                    'kengtaung',
                    'Homane',
                    'Minenaung',
                    'Panglong',
                ],
            ],
            [
                'name' => 'Shan State(North)',
                'townships' => [
                    'Hsipaw',
                    'Kyaukme',
                    'Namtu',
                    'Naungcho',
                    'Mabein',
                    'Mongmit',
                    'Kunlong',
                    'Konkyan',
                    'Laukkaing',
                    'Namhsan',
                    'Mantong',
                    'Kutkai',
                    'Namhkam',
                    'Muse',
                    'Tangyan',
                    'Mongyai',
                    'Lashio',
                    'Hsenwi',
                    'Namphan',
                    'Pangsang(Pansan)',
                    'Pansai',
                    'Mongmao',
                    'Matman',
                    'Hopang',
                    'Chinshwehaw',
                    'Tamoenye',
                    'Monekoe',
                    'Manhero',
                    'Namtit',
                ],
            ],
            [
                'name' => 'Shan State(East)',
                'townships' => [
                    'Kengtung',
                    'Minekote',
                    'Mongyang',
                    'Mongla',
                    'Tachileik',
                    'Monghsat',
                    'Mongtong',
                    'Mongping',
                    'Monghpayak',
                    'Mongyawng',
                    'Mongpauk',
                    'Kenglatt',
                    'Tarlay',
                    'Minekoke',
                    'Moneparkyin',
                    'Tongtar',
                    'Mineyu',
                ],
            ],
            [
                'name' => 'Ayeyarwady Region',
                'townships' => [
                    'Kangyidaunt',
                    'Kyaunggon',
                    'Kyonpyaw',
                    'Ngapudaw',
                    'Pathein',
                    'Yegyi',
                    'Thabaung',
                    'Kyaiklat',
                    'Dedaye',
                    'Pyapon',
                    'Bogale',
                    'Nyaungdon',
                    'Danubyu',
                    'Pantanaw',
                    'Maubin',
                    'Myaungmya',
                    'Wakema',
                    'Einme',
                    'Mawlamyinegyun',
                    'Labutta',
                    'Kyangin',
                    'Zalun',
                    'Myanaung',
                    'Lemyethna',
                    'Hinthada',
                    'Ingapu',
                    'Shwethaungyan',
                    'Ngayokekaung',
                    'Hainggyikyun',
                    'Ahmar',
                    'Pyinsalu',
                ],
            ],
            [
                'name' => 'Naypyidaw',
                'townships' => [
                    'Tatkone',
                    'Zabuthiri',
                    'Ottarathiri',
                    'Pobbathiri',
                    'Pyinmana',
                    'Lewe',
                    'Zeyarthiri',
                    'Dekkhinathiri',
                ],
            ],
        ];

        foreach ($locations as $location) {
            $region_state = RegionState::create(['name' => $location['name']]);

            if ($region_state) {
                foreach ($location['townships'] as $township) {
                    Township::create([
                        'name' => $township,
                        'region_state_id' => $region_state->id,
                    ]);
                }
            }
        }
    }
}
