version: "3"
services:
    laravel-app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: aungkaungmoe/meeting-app-image:v1.0.0
        container_name: meeting-app-container
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - meeting-app-network

    db:
        image: mysql:8.0
        container_name: meeting-app-db-container
        restart: unless-stopped
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=meeting
            - DB_USERNAME=root
            - DB_PASSWORD=password
        volumes:
            - db-data:/var/lib/mysql
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - meeting-app-network
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            timeout: 5s
            retries: 5

    nginx:
        image: nginx:alpine
        container_name: meeting-app-nginx-container
        restart: unless-stopped
        ports:
            - 80:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        networks:
            - meeting-app-network

networks:
    meeting-app-network:
        driver: bridge

volumes:
    db-data:
