networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge
services:
    mysql:
        image: mysql:8.0
        container_name: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_ROOT_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        ports:
            - "3306:3306"
        restart: unless-stopped
        tty: true
        volumes:
            - dbdata:/var/lib/mysql/
        networks:
            - backend
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 30s
            retries: 5
            start_period: 10s
            timeout: 10s

    app:
        build:
            context: .
            dockerfile: Docker/php.Dockerfile
        volumes:
            - .:/var/www/meeting:delegated
        ports:
            - "3000:3000"
            - "3001:3001"
            - "5173:5173"
            - "8080:8080"
        depends_on:
            - mysql
            - redis
        networks:
            - frontend
            - backend

    redis:
        image: redis:7
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - backend

    nginx:
        image: nginx:stable-alpine
        ports:
            - "80:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - frontend
            - backend

volumes:
    dbdata:
        driver: bridge
