name: Main workflow

on: [push]

jobs:
  linting:
    name: run static code analysis
    uses: ./.github/workflows/ci-lint.yml

  tests:
    name: run ci test
    needs: linting
    uses: ./.github/workflows/ci-test.yml

  # build-and-deploy:
  #     runs-on: ubuntu-latest
  #     needs: tests

  # steps:
  #     name: Checkout code
  #     uses: actions/checkout@v4
